-- GeneratedData.lua
-- Auto-generated by CombatLedger Companion. Do not edit manually.
-- This file is overwritten after each fight by the Companion app.
-- WoW loads it on every /reload but never writes to it.
CombatLedgerDB = nil
